### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 13835571914yp** [eneriz-daniel/MIBCI-QCNNs#3]
Using Windows operating system,Vivado HLS2020.1。 I encountered a problem while running the HLS simulation. like this

![Error](https://user-images.githubusercontent.com/53750417/172040959-b49b0cd1-b9b6-4970-8260-84d27f88bdd1.jpg)

![Error2](https://user-images.githubusercontent.com/53750417/172041000-d3845058-7148-40f7-af77-4fc2c62a8600.jpg)
![Error4](https://user-images.githubusercontent.com/53750417/172041147-0bf8cf3e-cc5d-4c81-bcf4-082a2d0ad1e3.jpg)

I would like to know how to solve this problem.

**Comment by eneriz-daniel** [comment]
Hi @13835571914yp ! Thanks for your interest in our work, it's great to see it may help others!

Unfortunately, I don't see anything that may be causing the problem. It's weird since you could successfully evaluate 340 samples.

To debug this, I would recommend you to run a floating-point test bench in a non-Vivado C/C++ compiler. In `MI-BCI.h` there is [this line](https://github.com/eneriz-daniel/MIBCI-QCNNs/blob/f2e94f559cb6345c385aead25506d83a3df3a0f0/MIBCI-QCNN.h#L21) that should automatically adjust all the dependence to enable the floating-point simulation. This will hopefully elp you to find the possible error causing this. Once you'll have checked this works outside Vivado HLS with floating point, you'll can then try to simulate it with fixed-point datatypes.

Another possible reason causing this is an issue with the generated dataset or the `.npy` loading from Vivado.

All the best,

Daniel

**Comment by 13835571914yp** [comment]
Hi Daniel.
I took your advice, adjust all the dependence.like this
![p1](https://user-images.githubusercontent.com/53750417/172564988-2f832293-d574-4025-81a1-7136cf2bfe78.jpg)
Strangely, still Windows OS. HLS2020.1.  HLS C simulation successful.

![p2](https://user-images.githubusercontent.com/53750417/172565318-2bb61a57-2429-41c1-8799-858ff55aceae.jpg)
Although the fixed point type of simulation I still did not find the cause of the error.Thanks again for your advice.
 
All the best

13835571914yp

**Comment by eneriz-daniel** [comment]
Hi @13835571914yp !

It might be some issue with the Vivado version, since I've tested this with Vivado HLS 2019.2.

You can also try to variate the fixed-point datatype parameters, to discard any kind of strange problem related with the default datatype.

All the best,
Daniel
